version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ./data/db:/data/db
    tty: true
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/bank-account --quiet
      interval: 30s
      timeout: 10s
      retries: 3
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_healthy
